version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-stretch
      - image: circleci/openjdk:stretch # move this in test only
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run tests
          command: npm test
